apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: cicd-app
